// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /users)
	CreateUser(c *gin.Context)

	// (GET /users/{userID})
	GetUserByID(c *gin.Context, userID UserID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.CreateUser(c)
}

// GetUserByID operation middleware
func (siw *ServerInterfaceWrapper) GetUserByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "userID" -------------
	var userID UserID

	err = runtime.BindStyledParameter("simple", false, "userID", c.Param("userID"), &userID)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userID: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetUserByID(c, userID)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router *gin.Engine, si ServerInterface) *gin.Engine {
	return RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router *gin.Engine, si ServerInterface, options GinServerOptions) *gin.Engine {

	errorHandler := options.ErrorHandler

	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/users", wrapper.CreateUser)

	router.GET(options.BaseURL+"/users/:userID", wrapper.GetUserByID)

	return router
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xWX2/bNhD/KsJtj7LoZB0QCBiwtc2CAEMxtOteijxcpLPMTiK54ymOYei7DyRlx38U",
	"zAWMvkm8fz/e/e6OG6hs56whIx7KDThk7EiI499nT3z/PnzV5CvWTrQ1UELvibP795CDDr8OZQk5GOxo",
	"FEYZ07+9ZqqhFO4pB18tqcPgTdYuaHphbRoYhiEoe2eNpxj3ltnyByu/297U4aCyRshI+ETnWl1hQKK+",
	"+gBns+f5R6YFlPCDermWSlKvotcU7fA6xkq2CKEySip5QvDZ0LOjSug7YOh3sY5A/I2trjFpXRKEn0Lx",
	"tAv2giKQ4ONYnW+C4Ng6YtGppjXK/wILoSCgGgliH79SJVNAvTZNS1kk4pY60XJ0tWPRKRDaHh+z8CTs",
	"WAH/io/4hXWtAyZs/zzQ0EKdn4iyC4LMuIaJu07AiHk5BdGhbidDpE4864bB9TsmFDo7QA7PM4tOzypb",
	"U0NmRs/COBNsotXIoWCwnQB58jS8Cu3bXUZnDr1fWa4vghFbt0TTd3lL5pebRLoJHmqzsNs2wEr28gR+",
	"jUvW2DKapsGrq1+bICgq271Mx49Rlt3+o7NPozqcsPsv6lyLQtnCctbYzLGNAHJodUVjH44Of3NYLSm7",
	"LuaQQ88Bx1LE+VKp1WpVYBQXlhs12nr1x/272w+fbmfXxbxYShcBiJY2uLuzs210yOGJ2CdIV8W8mAdF",
	"68ig01DCT/Eoj+M/ZlWFdkzdYr2cro3EM59hZmgVe7eA6JDjCLmvdzqR8GmDkJe3tl5fbPjtEX5iriTJ",
	"Dt/JFjveVNfz+WsBd3rqYIIOObw5x+h4+A85/Hy23d7mijSOtP8Sm93DQzhKtVKbtK2H4LehiZrdkWTB",
	"LHtcp41/WK47kiB9u46y/dfDl2mgLypqfF0MD5fJ6Zszc7N7V1w0o2H1ED9tr36YRHQ6S9KDHi2Vam2F",
	"7dJ6KTfOsgwKnVZPV6H1kDU+tjT2E4+1WWDfCpRwM78JvUem7wKO+BtgPAz/BQAA///xzikI0wkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
