version: "3.9"

services:
  postgresql:
    container_name: pg-go-template
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=go_template
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
