// Code generated by MockGen. DO NOT EDIT.
// Source: converter.go

// Package mock_response is a generated GoMock package.
package mock_response

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDecoderAdapter is a mock of DecoderAdapter interface.
type MockDecoderAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockDecoderAdapterMockRecorder
}

// MockDecoderAdapterMockRecorder is the mock recorder for MockDecoderAdapter.
type MockDecoderAdapterMockRecorder struct {
	mock *MockDecoderAdapter
}

// NewMockDecoderAdapter creates a new mock instance.
func NewMockDecoderAdapter(ctrl *gomock.Controller) *MockDecoderAdapter {
	mock := &MockDecoderAdapter{ctrl: ctrl}
	mock.recorder = &MockDecoderAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDecoderAdapter) EXPECT() *MockDecoderAdapterMockRecorder {
	return m.recorder
}

// Decode mocks base method.
func (m *MockDecoderAdapter) Decode(in, out interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", in, out)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decode indicates an expected call of Decode.
func (mr *MockDecoderAdapterMockRecorder) Decode(in, out interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockDecoderAdapter)(nil).Decode), in, out)
}
