openapi: "3.0.0"

info:
  title: Go-Template
  version: 1.0.0
  description: Template for go project
  contact:
    name: Rangga Eki Syahrial
    email: syahrialrangga11@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:{port}/api/v1
    description: api server
    variables:
      port:
        default: "8080"
        enum:
          - "8080"

paths:
  /users:
    post:
      tags:
        - Users
      description: Creates a new user.
      operationId: createUser
      requestBody:
        description: Create new user
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUser"
      responses:
        "200":
          description: user response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MultipleError"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    User:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
        email:
          type: string
    CreateUser:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
        email:
          type: string
          x-oapi-codegen-extra-tags:
            validate: email
        password:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    MultipleError:
      type: object
      required:
        - messages
      properties:
        messages:
          type: array
          items:
            type: object
            additionalProperties:
              type: array
              items:
                type: string
