name: CI

on:
  pull_request:

env:
  go_version: "1.18.3"
  golangci_version: "v1.47"

jobs:
  test:
    name: unit-test-lint
    # Using shared runner due to performance issue
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go v${{ env.go_version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go_version }}
      - name: run unit test
        run: |
          make ci-test

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go v${{ env.go_version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go_version }}
      - name: golangci-lint ${{ env.go_version }}
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.go_version }}
