name: CI

on:
  pull_request:

env:
  go_version: "1.18.3"
  GOPRIVATE: "github.com/kargotech"

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    name: unit-test-lint
    # Using shared runner due to performance issue
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go_version }}

      - name: Run Test Coverage
        run: make test-cover

  golangci-lint:
    name: golangci-lint
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go_version }}

      - run: make lint
